"""make ai fields nullable

Revision ID: 54d0b1752b90
Revises: 38b443051369
Create Date: 2026-09-24 11:36:57.190763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54d0b1752b90'
down_revision: Union[str, Sequence[str], None] = '38b443051369'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('analyses', 'video_format',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
    op.alter_column('analyses', 'tone',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
    op.alter_column('analyses', 'level',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
    op.alter_column('analyses', 'pace',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
    op.alter_column('analyses', 'overview',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('analyses', 'model_name',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('analyses', 'model_name',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('analyses', 'overview',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('analyses', 'pace',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
    op.alter_column('analyses', 'level',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
    op.alter_column('analyses', 'tone',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
    op.alter_column('analyses', 'video_format',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
    # ### end Alembic commands ###
